
enum Platform {
    PSN
    XBOX
}

enum Race {
    Human,
    Awoken,
    Exo
}

enum Gender {
    Male,
    Female
}

enum Class {
    Titan
    Warlock
    Hunter
}

enum SubclassType {
    Striker
    Defender
    Sunbreaker
    Stormcaller
    Voidwalker
    Sunsinger
    Bladedancer
    Nightstalker
    Gunslinger
}

enum EquipmentType {
    PrimaryWeapon
    SpecialWeapon
    HeavyWeapon
    Ghost
    Helmet
    Gauntlets
    ChestArmor
    LegArmor
    ClassArmor
    Artifact
    Emblem
    Shader
    Sparrow
    SparrowHorn
    Ship
    Emote
    Subclass
}

type Emblem {
    id: ID!
    name: String!
    iconPath: String!
    backgroundPath: String!
}

type Equipment {
    # the instance id of the item, the unique identifier for the item owned by this character
    id: ID!
    # the reference id of the item (it's hash) for looking up the base item in the manifest
    ref: ID!
    name: String!
    type: EquipmentType!
}

type CharacterStats {
    armor: Int!
    recovery: Int!
    agility: Int!
    intellect: Int!
    discipline: Int!
    strength: Int!
}

type Character {
    id: ID!
    class: Class!
    # subclass: Subclass!
    stats: CharacterStats!
    race: Race!
    gender: Gender!
    level: Int!
    light: Int!
    playTime: Int!
    equipment: [Equipment!]!
}

type Account {
    id: ID!
    username: String!
    platform: Platform!
    grimoireScore: Int!
    characters: [Character!]!
}

type Query {
    player(username: String!, platform: Platform) : Account
}
