
enum Platform {
    PSN
    XBOX
}

enum Race {
    Human,
    Awoken,
    Exo
}

enum Gender {
    Male,
    Female
}

enum Class {
    Titan
    Warlock
    Hunter
}

enum Subclass {
    Striker
    Defender
    Sunbreaker
    Stormcaller
    Voidwalker
    Sunsinger
    Bladedancer
    Nightstalker
    Gunslinger
}

type Emblem {
    id: ID!
    name: String!
    iconPath: String!
    backgroundPath: String!
}

type CharacterStats {
    armor: Int!
    recovery: Int!
    agility: Int!
    intellect: Int!
    discipline: Int!
    strength: Int!
}

type Character {
    id: ID!
    class: Class!
    # subclass: Subclass!
    stats: CharacterStats!
    race: Race!
    gender: Gender!
    level: Int!
    light: Int!
    playTime: Int!
}

type Account {
    id: ID!
    username: String!
    platform: Platform!
    grimoireScore: Int!
    characters: [Character!]!
}

type Query {
    player(username: String!, platform: Platform) : Account
}
